
remote_theme: pages-themes/minimal

title: News Representation of Social Service Agencies During COVID-19 in Singapore 
description: A corpus linguistics approach
github:
  zip_url: 
  another_url: https://github.com/gerardchung/ssa_covid_news.git

theme: jekyll-theme-minimal
